### ISSUE TITLE
有个bug不知道怎么修复

### ISSUE THREAD

**Issue by wangmchn** [allsome/LSYEvernote#1]
hey,@allsome
学到很多东西~很感谢，但是有个小bug困惑挺久，
当第一次点开某个cell的时候，直接用Pan手势dismiss，textView会忽然消失，不知道怎么引起的
但是第二次就不会出现这种情况
求解决求告知

**Comment by allsome** [comment]
@wangmchn ，感谢你的反馈，问题已解决

**Comment by wangmchn** [comment]
Great!
